-- CREATING TABLES --

CREATE TABLE "Roles" (
  "RoleID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleName" varchar(50) UNIQUE NOT NULL,
  "Description" varchar(255)
);

CREATE TABLE "Users" (
  "UserID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleID" int NOT NULL,
  "FirstName" varchar(100),
  "LastName" varchar(100),
  "Email" varchar(255) UNIQUE NOT NULL,
  "PasswordHash" varchar(255) NOT NULL,
  "IsActive" boolean NOT NULL DEFAULT true,
  "DateCreated" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Instructors" (
  "InstructorID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int UNIQUE NOT NULL,
  "Bio" text,
  "OfficeHours" varchar(255),
  "IsVerified" boolean DEFAULT false
);

CREATE TABLE "Students" (
  "StudentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int UNIQUE NOT NULL,
  "EnrollmentDate" date DEFAULT CURRENT_DATE,
  "StudentStatus" varchar(50)
);

CREATE TABLE "Categories" (
  "CategoryID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CategoryName" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "Courses" (
  "CourseID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "InstructorID" int NOT NULL,
  "CategoryID" int NOT NULL,
  "Title" varchar(255) NOT NULL,
  "Description" text,
  "Duration" int,
  "Price" decimal(10,2) DEFAULT 0,
  "IsPublished" boolean DEFAULT false,
  "DateCreated" timestamp DEFAULT CURRENT_TIMESTAMP,
  "IsDeleted" boolean NOT NULL DEFAULT false
);

CREATE TABLE "Sections" (
  "SectionID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CourseID" int NOT NULL,
  "Title" varchar(255) NOT NULL,
  "OrderNumber" int NOT NULL
);

CREATE TABLE "Lessons" (
  "LessonID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SectionID" int NOT NULL,
  "Title" varchar(255) NOT NULL,
  "ContentType" varchar(50),
  "ContentURL" text,
  "Duration" int,
  "LastModifiedByUserID" int,
  "LastModifiedDate" timestamp
);

CREATE TABLE "Resources" (
  "ResourceID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LessonID" int NOT NULL,
  "FileName" varchar(255) NOT NULL,
  "FileType" varchar(50),
  "FileURL" text NOT NULL
);

CREATE TABLE "CourseEnrollments" (
  "EnrollmentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StudentID" int NOT NULL,
  "CourseID" int NOT NULL,
  "EnrollmentDate" timestamp DEFAULT CURRENT_TIMESTAMP,
  "CompletionDate" timestamp,
  "Status" varchar(50)
);

CREATE TABLE "StudentProgress" (
  "ProgressID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EnrollmentID" int NOT NULL,
  "LessonID" int NOT NULL,
  "IsCompleted" boolean NOT NULL DEFAULT false,
  "DateCompleted" timestamp
);

CREATE TABLE "Assignments" (
  "AssignmentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CourseID" int NOT NULL,
  "Title" varchar(255) NOT NULL,
  "Description" text,
  "MaxPoints" int DEFAULT 100,
  "DueDate" timestamp
);

CREATE TABLE "Grades" (
  "GradeID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AssignmentID" int NOT NULL,
  "StudentID" int NOT NULL,
  "PointsEarned" int NOT NULL,
  "Feedback" text,
  "LastModifiedByUserID" int,
  "LastModifiedDate" timestamp
);

CREATE TABLE "AuditLog" (
  "LogID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserID" int NOT NULL,
  "ActionType" varchar(50),
  "EntityName" varchar(100),
  "EntityID" int NOT NULL,
  "Timestamp" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Comments" (
  "CommentID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LessonID" int NOT NULL,
  "UserID" int NOT NULL,
  "CommentText" text NOT NULL,
  "DatePosted" timestamp DEFAULT CURRENT_TIMESTAMP,
  "IsDeleted" boolean NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX ON "CourseEnrollments" ("StudentID", "CourseID");
CREATE UNIQUE INDEX ON "StudentProgress" ("EnrollmentID", "LessonID");

-- FOREIGN KEYS --

-- 1:N
ALTER TABLE "Users" ADD CONSTRAINT "user_role" FOREIGN KEY ("RoleID") REFERENCES "Roles" ("RoleID");

-- 1:1
ALTER TABLE "Instructors" ADD CONSTRAINT "user_instructor" FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");
ALTER TABLE "Students" ADD CONSTRAINT "user_student" FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");

ALTER TABLE "Courses" ADD CONSTRAINT "course_instructor" FOREIGN KEY ("InstructorID") REFERENCES "Instructors" ("InstructorID");
ALTER TABLE "Courses" ADD CONSTRAINT "course_category" FOREIGN KEY ("CategoryID") REFERENCES "Categories" ("CategoryID");
ALTER TABLE "Sections" ADD CONSTRAINT "section_course" FOREIGN KEY ("CourseID") REFERENCES "Courses" ("CourseID");
ALTER TABLE "Lessons" ADD CONSTRAINT "lesson_section" FOREIGN KEY ("SectionID") REFERENCES "Sections" ("SectionID");
ALTER TABLE "Resources" ADD CONSTRAINT "resource_lesson" FOREIGN KEY ("LessonID") REFERENCES "Lessons" ("LessonID");

ALTER TABLE "CourseEnrollments" ADD CONSTRAINT "enrollment_student" FOREIGN KEY ("StudentID") REFERENCES "Students" ("StudentID");
ALTER TABLE "CourseEnrollments" ADD CONSTRAINT "enrollment_course" FOREIGN KEY ("CourseID") REFERENCES "Courses" ("CourseID");
ALTER TABLE "StudentProgress" ADD CONSTRAINT "progress_enrollment" FOREIGN KEY ("EnrollmentID") REFERENCES "CourseEnrollments" ("EnrollmentID");
ALTER TABLE "StudentProgress" ADD CONSTRAINT "progress_lesson" FOREIGN KEY ("LessonID") REFERENCES "Lessons" ("LessonID");

ALTER TABLE "Assignments" ADD CONSTRAINT "assignment_course" FOREIGN KEY ("CourseID") REFERENCES "Courses" ("CourseID");
ALTER TABLE "Grades" ADD CONSTRAINT "grade_assignment" FOREIGN KEY ("AssignmentID") REFERENCES "Assignments" ("AssignmentID");
ALTER TABLE "Grades" ADD CONSTRAINT "grade_student" FOREIGN KEY ("StudentID") REFERENCES "Students" ("StudentID");

ALTER TABLE "AuditLog" ADD CONSTRAINT "audit_user" FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");
ALTER TABLE "Comments" ADD CONSTRAINT "comment_lesson" FOREIGN KEY ("LessonID") REFERENCES "Lessons" ("LessonID");
ALTER TABLE "Comments" ADD CONSTRAINT "comment_user" FOREIGN KEY ("UserID") REFERENCES "Users" ("UserID");
ALTER TABLE "Lessons" ADD CONSTRAINT "lesson_modifier" FOREIGN KEY ("LastModifiedByUserID") REFERENCES "Users" ("UserID");
ALTER TABLE "Grades" ADD CONSTRAINT "grade_modifier" FOREIGN KEY ("LastModifiedByUserID") REFERENCES "Users" ("UserID");

-- INDICES --

-- FOR 'Courses' TABLE

-- 1. A compound B-Tree index to speed up filtering of the course catalog.
-- Optimizes queries that filter by deletion status, publication status, and category.
CREATE INDEX idx_courses_catalog 
ON "Courses" ("IsDeleted", "IsPublished", "CategoryID");

-- 1.2. A B-Tree index to speed up searching for student progress by completion status.
-- Useful for getting a list of incomplete or completed lessons.
CREATE INDEX idx_progress_completed 
ON "StudentProgress" ("IsCompleted");

-- 2. GIN index for full-text search.
-- using the standard 'english' dictionary for morphological analysis.

-- 2.1. Create a generated SearchVector column
-- It combines the title and description, tokenizes them, and stores the result.
ALTER TABLE "Courses" ADD COLUMN "SearchVector" tsvector
    GENERATED ALWAYS AS (to_tsvector('english', "Title" || ' ' || "Description")) STORED;

-- 2.2. Create a GIN index on this vector.
-- This makes keyword searching fast.
CREATE INDEX idx_courses_search 
ON "Courses" USING GIN ("SearchVector");