name: Deploy Docs to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy docs to root
        run: cp -r ../sem4/OOOP/lab1/lab1_a/new_project/docs ./docs
      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Deploy docs to GitHub Pages" || echo "No changes to commit"
          git push origin main
